"""empty message

Revision ID: 363b3e881f8a
Revises: 7371c0e9a94e
Create Date: 2021-07-22 08:57:23.549298

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '363b3e881f8a'
down_revision = '7371c0e9a94e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jsonstring', 'jsonString',
               existing_type=mysql.MEDIUMTEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jsonstring', 'jsonString',
               existing_type=mysql.MEDIUMTEXT(),
               nullable=True)
    # ### end Alembic commands ###
